[package]
name = "mlx-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
    "accelerate",
    "metal",
]

accelerate = []
metal = []

[dependencies]
cxx = "1"
half = "2" # TODO: Should this be optional?

[build-dependencies]
cxx-build = "1"
pkg-config = "0.3"
