[package]
name = "mlx-sys"
version.workspace = true
edition.workspace = true
description = "Rust bindings for mlx"
readme = "README.md"
authors = ["Minghua Wu"]
license.workspace = true
repository.workspace = true
homepage = "https://github.com/minghuaw/mlx-rs"
documentation = "https://minghuaw.github.io/mlx-rs/doc/mlx_sys/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
    "accelerate",
    "metal",
]

accelerate = []
metal = []

[dependencies]
cxx = "1"
half = { version = "2", optional = true }
libc = "0.2"

[build-dependencies]
cxx-build = "1"
pkg-config = "0.3"
