[package]
name = "mlx-sys"
version = "0.1.0-alpha"
edition = "2021"
description = "Rust bindings for mlx"
readme = "README.md"
authors = ["Minghua Wu"]
license = "MIT"
repository = "https://github.com/minghuaw/mlx-rs"
homepage = "https://github.com/minghuaw/mlx-rs"
documentation = "https://docs.rs/mlx-sys"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = [
    "accelerate",
    "metal",
]

accelerate = []
metal = []

[dependencies]
cxx = "1"
half = { version = "2", optional = true }
libc = "0.2"

[build-dependencies]
cxx-build = "1"
pkg-config = "0.3"
