[package]
name = "mlx-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cxx = "1"
autocxx = "0.26"

[build-dependencies]
autocxx-build = "0.26"
miette = { version = "5", features = ["fancy"] }
