[package]
name = "mlx-rs"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlx-sys = { workspace = true }
cxx = { workspace = true }
half = { workspace = true, optional = true }